stages:
  - install
  - build

install:
  stage: install
  image: ubuntu:24.04
  script:
    - chmod +x ./scripts/install.sh
    - ./scripts/install.sh
  artifacts:
    paths:
      - /var/log/
    expire_in: 1 week

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker info
  script:
    - chmod +x ./scripts/build.sh
    - ./scripts/build.sh
  only:
    - main
    - tags