version: '3.8'

services:
  # Server side with stunnel and nginx file server
  tls-server:
    build:
      context: ./server
    container_name: tls-server
    hostname: tls-server
    ports:
      - "8000:8000"  # Direct access to nginx
      - "8443:8443"  # Standard TLS tunnel (TLS 1.3)
      - "8444:8444"  # NULL cipher TLS tunnel (TLS 1.2)
    networks:
      - test-network
    volumes:
      - ./shared:/shared
      - ./config:/config
      - ./data:/data
    cap_add:
      - NET_ADMIN  # Required for tc network traffic control

  # Client side with stunnel (TLS 1.3)
  tls-client:
    build:
      context: ./client
    container_name: tls-client
    hostname: tls-client
    networks:
      - test-network
    ports:
      - "9000:9000"  # Expose TLS 1.3 tunnel endpoint to host
    depends_on:
      - tls-server
    volumes:
      - ./shared:/shared
      - ./config:/config
    cap_add:
      - NET_ADMIN  # Required for tc network traffic control
      
  # Client side with stunnel using TLS 1.2 and NULL cipher
  tls-null:
    build:
      context: ./tls-null
    container_name: tls-null
    hostname: tls-null
    networks:
      - test-network
    ports:
      - "9001:9001"  # Expose TLS 1.2 NULL cipher tunnel endpoint to host
    depends_on:
      - tls-server
    volumes:
      - ./shared:/shared
      - ./config:/config
    cap_add:
      - NET_ADMIN  # Required for tc network traffic control

  # SSH forwarding container
  ssh:
    build:
      context: ./ssh
    container_name: ssh
    hostname: ssh
    networks:
      - test-network
    ports:
      - "7000:7000"  # SSH port forwarding to nginx
      - "2222:22"    # Expose SSH port for external connections
    depends_on:
      - tls-server
    volumes:
      - ./shared:/shared
      - ./config:/config
    cap_add:
      - NET_ADMIN  # Required for tc network traffic control
      
  # HAProxy TCP proxy container
  haproxy:
    image: haproxy:2.6.14
    container_name: haproxy
    hostname: haproxy
    networks:
      - test-network
    ports:
      - "7100:7100"  # HAProxy TCP proxy to tls-server
    depends_on:
      - tls-server
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./shared:/shared
    cap_add:
      - NET_ADMIN  # Required for tc network traffic control
    command: ["haproxy", "-f", "/usr/local/etc/haproxy/haproxy.cfg", "-db"]
      
  # Nginx TCP proxy container
  nginx-proxy:
    build:
      context: ./nginx-proxy
    container_name: nginx-proxy
    hostname: nginx-proxy
    networks:
      - test-network
    ports:
      - "7200:7200"  # Nginx TCP proxy to tls-server
      - "7300:7300"  # Nginx NAT implementation to tls-server
    depends_on:
      - tls-server
    volumes:
      - ./shared:/shared
      - ./config:/config
    cap_add:
      - NET_ADMIN  # Required for tc network traffic control
      - NET_RAW    # Required for NAT functionality
      - SYS_ADMIN  # Required for sysctl commands
      
  # Pure iptables NAT container (no proxy server)
  iptables-nat:
    build:
      context: ./iptables-nat
    container_name: iptables-nat
    hostname: iptables-nat
    networks:
      - test-network
    ports:
      - "7400:7400"  # Pure iptables NAT to tls-server
    depends_on:
      - tls-server
    volumes:
      - ./shared:/shared
    cap_add:
      - NET_ADMIN  # Required for iptables
      - NET_RAW    # Required for NAT functionality

networks:
  test-network:
    driver: bridge
