version: '3.8'

services:
  # Server side with stunnel and nginx file server
  tls-server:
    image: scistream-benchmark:latest
    container_name: tls-server
    hostname: tls-server
    ports:
      - "8000:8000"  # Direct access to nginx
      - "8443:8443"  # Standard TLS tunnel (TLS 1.3)
      - "8444:8444"  # NULL cipher TLS tunnel (TLS 1.2)
      - "2223:22"    # SSH server (changed host port from 22 to 2223)
    networks:
      - test-network
    volumes:
      - ./shared:/shared
      - ./config:/config
      - ./data:/data
      - ./scripts/startup/tls-server.sh:/start.sh
    cap_add:
      - NET_ADMIN  # Required for tc network traffic control
    command: ["/start.sh"]

  # Client side with stunnel (TLS 1.3)
  tls-client:
    image: scistream-benchmark:latest
    container_name: tls-client
    hostname: tls-client
    networks:
      - test-network
    ports:
      - "9000:9000"  # Expose TLS 1.3 tunnel endpoint to host
    depends_on:
      - tls-server
    volumes:
      - ./shared:/shared
      - ./config:/config
      - ./scripts/startup/tls-client.sh:/start.sh
    cap_add:
      - NET_ADMIN  # Required for tc network traffic control
    command: ["/start.sh"]
      
  # Client side with stunnel using TLS 1.2 and NULL cipher
  tls-null:
    image: scistream-benchmark:latest
    container_name: tls-null
    hostname: tls-null
    networks:
      - test-network
    ports:
      - "9001:9001"  # Expose TLS 1.2 NULL cipher tunnel endpoint to host
    depends_on:
      - tls-server
    volumes:
      - ./shared:/shared
      - ./config:/config
      - ./scripts/startup/tls-null.sh:/start.sh
    cap_add:
      - NET_ADMIN  # Required for tc network traffic control
    command: ["/start.sh"]

  # SSH forwarding container
  ssh:
    image: scistream-benchmark:latest
    container_name: ssh
    hostname: ssh
    networks:
      - test-network
    ports:
      - "7000:7000"  # SSH port forwarding to nginx
      - "2222:22"    # Expose SSH port for external connections
    depends_on:
      - tls-server
    volumes:
      - ./shared:/shared
      - ./config:/config
      - ./scripts/startup/ssh-tunnel.sh:/start.sh
      - ./ssh/ssh_config:/tmp/ssh_config
    privileged: true  # Required for full system access
    cap_add:
      - NET_ADMIN  # Required for tc network traffic control
    command: ["/start.sh"]
      
  # HAProxy TCP proxy container (using official image)
  haproxy:
    image: haproxy:2.6.14
    container_name: haproxy
    hostname: haproxy
    networks:
      - test-network
    ports:
      - "7100:7100"  # HAProxy TCP proxy to tls-server
    depends_on:
      - tls-server
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./shared:/shared
      - ./scripts/startup/haproxy.sh:/start.sh
    cap_add:
      - NET_ADMIN  # Required for tc network traffic control
    command: ["/start.sh"]
  # Pure iptables NAT container (no proxy server)
  iptables-nat:
    image: scistream-benchmark:latest
    container_name: iptables-nat
    hostname: iptables-nat
    networks:
      - test-network
    ports:
      - "7400:7400"  # Pure iptables NAT to tls-server
    depends_on:
      - tls-server
    volumes:
      - ./shared:/shared
      - ./scripts/startup/iptables-nat.sh:/start.sh
    cap_add:
      - NET_ADMIN  # Required for iptables
      - NET_RAW    # Required for NAT functionality
    command: ["/start.sh"]

networks:
  test-network:
    driver: bridge