version: '3.8'

x-common-settings: &common-settings
  image: castroflaviojr/scistream-benchmark:latest
  cap_add:
    - NET_ADMIN
  restart: unless-stopped

services:
  nginx-server:
    <<: *common-settings
    container_name: nginx-server
    hostname: nginx-server
    profiles: ["producer"]
    ports:
      - "8000:8000"
    volumes:
      - ../data:/data
      - ../shared:/shared
      - ../config:/config
      - ../scripts/startup/nginx-server.sh:/start.sh
    networks:
      - producer-network
    command: ["/start.sh"]
  
  tunnel-server:
    <<: *common-settings
    container_name: tunnel-server
    hostname: tunnel-server
    profiles: ["tunnel-server"]
    ports:
      - "8443:8443"
      - "8444:8444"
      - "2222:22"
    volumes:
      - ../shared:/shared
      - ../config:/config
      - ../scripts/startup/tunnel-server.sh:/start.sh
    networks:
      - tunnel-network
    command: ["/start.sh"]
    
  haproxy-server:
    image: haproxy:2.6.14
    container_name: haproxy-server
    hostname: haproxy-server
    profiles: ["tunnel-server"]
    ports:
      - "7200:7200"
    volumes:
      - ../config/haproxy/haproxy-server.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ../shared:/shared
      - ../scripts/startup/haproxy-server.sh:/start.sh
    cap_add:
      - NET_ADMIN
    networks:
      - tunnel-network
    command: ["/start.sh"]
    restart: unless-stopped

  tls-client:
    <<: *common-settings
    container_name: tls-client
    hostname: tls-client
    profiles: ["tunnel-client"]
    ports:
      - "9000:9000"
    volumes:
      - ../shared:/shared
      - ../config:/config
      - ../scripts/startup/tls-client.sh:/start.sh
    networks:
      - client-network
    command: ["/start.sh"]
      
  tls-null:
    <<: *common-settings
    container_name: tls-null
    hostname: tls-null
    profiles: ["tunnel-client"]
    ports:
      - "9001:9001"
    volumes:
      - ../shared:/shared
      - ../config:/config
      - ../scripts/startup/tls-null.sh:/start.sh
    networks:
      - client-network
    command: ["/start.sh"]

  ssh:
    <<: *common-settings
    container_name: ssh
    hostname: ssh
    profiles: ["tunnel-client"]
    ports:
      - "7000:7000"
    volumes:
      - ../shared:/shared
      - ../config:/config
      - ../scripts/startup/ssh-tunnel.sh:/start.sh
      - ../config/ssh/ssh_config:/tmp/ssh_config
    networks:
      - client-network
    command: ["/start.sh"]
      
  haproxy:
    image: haproxy:2.6.14
    container_name: haproxy
    hostname: haproxy
    profiles: ["tunnel-client"]
    ports:
      - "7100:7100"
    volumes:
      - ../config/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ../shared:/shared
      - ../scripts/startup/haproxy.sh:/start.sh
    cap_add:
      - NET_ADMIN
    networks:
      - client-network
    command: ["/start.sh"]
    restart: unless-stopped
  
  haproxy-cascade:
    image: haproxy:2.6.14
    container_name: haproxy-cascade
    hostname: haproxy-cascade
    profiles: ["tunnel-client"]
    ports:
      - "7300:7300"
    volumes:
      - ../config/haproxy/haproxy-cascade.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ../shared:/shared
      - ../scripts/startup/haproxy-cascade.sh:/start.sh
    cap_add:
      - NET_ADMIN
    networks:
      - client-network
    command: ["/start.sh"]
    restart: unless-stopped
    
  iptables-nat:
    <<: *common-settings
    container_name: iptables-nat
    hostname: iptables-nat
    profiles: ["tunnel-client"]
    ports:
      - "7400:7400"
    volumes:
      - ../shared:/shared
      - ../config:/config
      - ../scripts/startup/iptables-nat.sh:/start.sh
    cap_add:
      - NET_RAW
    networks:
      - client-network
    command: ["/start.sh"]

networks:
  producer-network:
    driver: bridge
  tunnel-network:
    driver: bridge
  client-network:
    driver: bridge