version: '3.8'

services:
  # Server side with stunnel server and SSH server
  tunnel-server:
    image: scistream-benchmark:latest
    container_name: tunnel-server
    hostname: tunnel-server
    ports:
      - "8443:8443"  # Standard TLS tunnel (TLS 1.3)
      - "8444:8444"  # NULL cipher TLS tunnel (TLS 1.2)
      - "2222:22"    # SSH access for tunneling (exposed on 2222)
    volumes:
      - ../shared:/shared
      - ../config:/config
      - ../scripts/startup/tunnel-server.sh:/start.sh
    cap_add:
      - NET_ADMIN  # Required for tc network traffic control
    networks:
      - tunnel-network
    command: ["/start.sh"]
    
  # HAProxy server for forwarding to producer
  haproxy-server:
    image: haproxy:2.6.14
    container_name: haproxy-server
    hostname: haproxy-server
    ports:
      - "7200:7200"  # HAProxy TCP proxy to nginx-server
    volumes:
      - ../config/haproxy/haproxy-server.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ../shared:/shared
      - ../scripts/startup/haproxy-server.sh:/start.sh
    cap_add:
      - NET_ADMIN  # Required for tc network traffic control
    networks:
      - tunnel-network
    command: ["/start.sh"]

networks:
  tunnel-network:
    driver: bridge